tap "ethereum/ethereum"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "linuxkit/linuxkit"
tap "pivotal/tap"
tap "sammy007/cryptonight"
tap "web3j/web3j"
brew "amazon-ecs-cli"
brew "python"
brew "ansible"
brew "autoconf"
brew "autojump"
brew "awscli"
brew "bitcoin"
brew "brew-cask-completion"
brew "cfssl"
brew "circleci"
brew "cowsay"
brew "docker-machine-driver-xhyve"
brew "dos2unix"
brew "etcd"
brew "ffmpeg"
brew "git"
brew "git-flow-avh"
brew "glide"
brew "googler"
brew "grafana"
brew "httpie"
brew "inetutils", link: false
brew "ipfs"
brew "jenv"
brew "jq"
brew "kops"
brew "kubernetes-helm"
brew "libpcap"
brew "lolcat"
brew "mas"
brew "mkdocs"
brew "mongodb"
brew "nginx"
brew "nmap"
brew "node"
brew "nvm"
brew "postgresql"
brew "prometheus"
brew "protobuf"
brew "redis"
brew "siege"
brew "tcptraceroute"
brew "telnet"
brew "tig"
brew "tor"
brew "tree"
brew "unrar"
brew "watch"
brew "websocketd"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "linuxkit/linuxkit/linuxkit", args: ["HEAD"]
brew "pivotal/tap/springboot"
cask "atom"
cask "bettertouchtool"
cask "bitcoin-core"
cask "bitmessage"
cask "dbeaver-community"
cask "discord"
cask "disk-inventory-x"
cask "docker-edge"
cask "dropbox"
cask "electrum"
cask "exodus"
cask "firefox"
cask "flux"
cask "font-consolas-for-powerline"
cask "font-source-code-pro-for-powerline"
cask "ganache"
cask "gitter"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "keybase"
cask "lastpass"
cask "ledger-live"
cask "libreoffice"
cask "mycrypto"
cask "ngrok"
cask "notion"
cask "osxfuse"
cask "pgadmin4"
cask "postgres"
cask "postman"
cask "remember-the-milk"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "videostream"
cask "visual-studio-code"
cask "xquartz"
cask "zoomus"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "iPhoto", id: 408981381
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Twitter", id: 409789998
mas "Typist", id: 415166115
mas "Xcode", id: 497799835
